apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: '{{ values.name }}-on-push'
  annotations:
    pipelinesascode.tekton.dev/on-event: "[push]"
    pipelinesascode.tekton.dev/on-target-branch: "[{{ values.defaultBranch }}]"
    pipelinesascode.tekton.dev/max-keep-runs: "2"
    pipelinesascode.tekton.dev/pipeline: "{{values.rawUrl}}/pac/pipelines/docker-build-ai-rhdh-push-gitops.yaml"
    pipelinesascode.tekton.dev/task-0: "{{values.rawUrl}}/pac/tasks/init.yaml"
    pipelinesascode.tekton.dev/task-1: "{{values.rawUrl}}/pac/tasks/git-clone.yaml"
    pipelinesascode.tekton.dev/task-2: "{{values.rawUrl}}/pac/tasks/buildah-ai-rhdh.yaml"
    pipelinesascode.tekton.dev/task-3: "{{values.rawUrl}}/pac/tasks/update-deployment-gitops.yaml"
    pipelinesascode.tekton.dev/task-4: "{{values.rawUrl}}/pac/tasks/show-sbom-rhdh.yaml"
    pipelinesascode.tekton.dev/task-5: "{{values.rawUrl}}/pac/tasks/summary.yaml"
spec:
  params:
    - name: dockerfile
      value: '{{ values.dockerfile }}'
    - name: git-url
      value: '{{repo_url}}'
    - name: image-expires-after
      value: 5d
    - name: output-image
      value: '{{ values.image }}:{{revision}}'
    - name: path-context
      value: '{{ values.buildContext }}'
    - name: revision
      value: '{{revision}}'
    - name: gitops-auth-secret-name
      value: '{{ values.gitopsSecretName }}'
  pipelineRef:
    name: docker-build-ai-rhdh-push-gitops
  workspaces:
    - name: git-auth
      secret:
        secretName: "{{ git_auth_secret }}"
    - name: gitops-auth
      secret:
        secretName: $(params.gitops-auth-secret-name)
    - name: workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
